version: 0.2

phases:
  pre_build:
    commands:
      - echo "--- 환경 변수 점검 ---"
      - echo "Account ID -> $AWS_ACCOUNT_ID"
      - echo "Region -> $AWS_DEFAULT_REGION"
      - echo "Image Name -> $ImageName"
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$ImageName
      - echo "Final URI -> $REPOSITORY_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo "--- 현재 위치의 파일 목록 ---"
      - ls -al
      - echo "--- 도커 빌드 시작 ---"
      # 만약 폴더가 없으면 아래 줄을 [ docker build -t $REPOSITORY_URI:latest . ] 로 수정하세요.
      - docker build -t $REPOSITORY_URI:latest -f ticketing-was/Dockerfile ./ticketing-was
  post_build:
    commands:
      - echo "--- 로컬에 생성된 이미지 확인 ---"
      - docker images  # 빌드된 이미지가 목록에 있는지 확인하는 핵심 명령어
      - echo "--- ECR 푸시 시도 ---"
      - docker push $REPOSITORY_URI:latest